version: '3'

services:
  activiti-admin:
    image: jylups/activiti-admin
    ports: 
     - "8888:8080"
    environment:
     - "JAVA_OPTS=-Drest.app.host=http://host.docker.internal -Drest.app.port=9883 -Drest.app.contextroot= -Drest.app.restroot="
